version: '3'
services:
    bot:
        build: .
        ports:
            - 5000:5000
        volumes:
            - .:/src
        environment:
            - BOT_TOKEN
            - PROTOCOL
            - FQDN
            - XERO_KEY
            - XERO_SECRET
